services:
  mysqldb:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: segundocerebro_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 20s

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - MYSQLHOST=mysqldb
      - MYSQLPORT=3306
      - MYSQLDATABASE=segundocerebro_db
      - MYSQLUSER=root
      - MYSQLPASSWORD=root
      - DDL_AUTO=update
      - JWT_SECRET=FrQuOQySCOJJhmn4OCFCpSKFbECJ0Fg6e9JmFlg4Ebo=
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USERNAME=tiagofef@gmail.com
      - SMTP_PASSWORD=ipgswyemxlucjyyz
    depends_on:
      mysqldb:
        condition: service_healthy