spring.datasource.hikari.initialization-fail-timeout=30000
spring.datasource.hikari.connection-timeout=30000
api.security.token.secret=${JWT_SECRET:FrQuOQySCOJJhmn4OCFCpSKFbECJ0Fg6e9JmFlg4Ebo=}
spring.jpa.hibernate.ddl-auto=update